### ISSUE TITLE
[Questions] On planification

### ISSUE THREAD

**Issue by ghost** [joehakimrahme/Agros#10]
Q1. Is Agros' intended to be a "real" terminal shell (i.e. like csh, ksh, bash, zsh, etc...) or is it meant to be a program run within another classic shell (i.e. you launch a terminal running bash for example, then you run Agros)? 
Q2. I've noticed you can exit Agros using C-c => bash still has control over processes running in the terminal. Isn't that a bit dangerous for an lshell? I guess the answer on how to solve this is largely dependent on Q1.
Q3. Does Agros have a plan? Do some features have priority over others? If so, which?
Q4. What are the real advantages of a limited shell? Can't we do the same thing using sudo, for example?

Finally, a minor low-priority technical issue: I tried running Agros from another laptop at home. It wouldn't compile (this deserves a separate post with more details on the error, but I won't burden you with that for now)

**Comment by joehakimrahme** [comment]
Questions are a little large.

Q1. As far as the interactive part of those shells goes, yes, absolutely. Maybe one day I would start considering a scripting engine, but for now I think of it as a limited interactive shell. For this there's one main condition: it is that we find a way to disable the "check validity". My idea would be to define something like this in the conf file: allowed=*

From here there are certain cool projects like job control (fg, bg, &), signals and stuff like that.

Q2. I already answered before: yes AGROS should support signals. It's not that difficult to do; we simply have to use the kill() UNIX function. But first I give priority to Readline, in order to define a proper interactive framework.

Q3. I don't have any particular plan, I take suggestions as they go. But I have to admit that I follow mainly lshell for inspiration. 

Apart from the projects you know (signals, job control, readline, syslog, am I forgetting anything?) there's a big project of defining per user configuration. Lshell already does that. So you can define something like "If I log as user foo, have these commands allowed, but as user bar, or any user from the group XXX have this other conf. Else, use the one by default". 

Q4. I hope there are! I hope I'm not wasting my time! :D

But here's a more serious answer. Much like most great things in this world, lshell, AGROS older brother, was created out of a necessity. Its creator wanted to access his home router remotely. Obviously it bothered him to open such a breach in the security of his home system. 

He only needed a bunch of harmless commands to perform on the router anyway. BAM! lshell is born. It gives two main protections:
- Protection from intruders, limiting them to harmless commands (like ls, cat and ps for instance). 
- Protection from yourself, to avoid accidentally entering a harmful command. (Kinda like the motive behind sudo, as you should not be looged as root)

Now if you're wondering why AGROS since lshell exists, then it's different. Lshell is far more advanced and complex than AGROS. It can detect whether you are logging in remotely (ssh, rsync, ...) or on the same machine. It supports sudo. So much more. But it has one disadvantage: it's coded in Python. 

Python is probably the best language ever to code in. Especially for such a project. But as a shell, I think most users would prefer to have binaries. The only compiled language I know is C. AGROS is born. 

I don't know if I ever told you that, but AGROS stands rightfully for AGROS Got Rid Of the Snake. I'm pretty proud of the name.

**Comment by joehakimrahme** [comment]
Q1 is done. Since version 0.2.1, you can define \* as your allowed commands. 

Next is to try to define AGROS as default login shell.

**Comment by joehakimrahme** [comment]
Q1 is done. Since version 0.2.1, you can define \* as your allowed commands. 

Next is to try to define AGROS as default login shell.
